### ISSUE TITLE
Use of the terra package?

### ISSUE THREAD

**Issue by mcoghill** [mlr-org/mlr3spatial#3]
I just found this package and thought that I should plug the [terra](https://github.com/rspatial/terra) package. It's described as the replacement for the raster package and in my experience it's been a much quicker and smoother experience. I'm not sure of the lengths that you would need to go to in order to implement terra over raster, but I just wanted to include this since lots of work has already gone into writing a faster raster package.

**Comment by pat-s** [comment]
Jup, we are aware of {terra} and might probably built on it right from the start.

**Comment by pat-s** [comment]
@mcoghill We have implemented **early** support for handling {terra} objects. {raster} is in fact more tricky since it is not able to store/handle factor variables, which makes it complicated for classification tasks.

Things are not yet fixed and might change in the near future, but you might be interested in having a look at it - also at the [benchmarking vignette](https://mlr3spatial.mlr-org.com/articles/benchmark.html).
